### ISSUE TITLE
Converting Between Julian and Gregorian Not Showing Difference

### ISSUE THREAD

**Issue by naftulikay** [cocainefarm/julianday#4]
Prior to January 31st, 1918, Russia was using [old style](https://en.wikipedia.org/wiki/Old_Style_and_New_Style_dates#Russia), i.e. Julian, dates, and the calendar was then corrected by moving February 1st to February 14th to synchronize the calendar with the rest of the world's Gregorian calendar.

When I do things like this, I don't see the dates being translated at all:

```rust
let old_style = NaiveDate::from_ymd(1917, 12, 1);
let new_style = JulianDay::from(old_style.clone()).to_date();

println!("OS: {}, NS: {}", old_style, new_style);
```

This prints: `OS: 1917-12-01, NS: 1917-12-01`.

Am I using the library incorrectly? Given a date in Julian, how can I translate that to Gregorian, and vice versa?

**Comment by maxaudron** [comment]
This library provides conversions for [Julian Days](https://en.wikipedia.org/wiki/Julian_day) which don't relate to the Julian Calendar. There is no calendar conversion happening at all.

I found the https://docs.rs/icu_calendar library, which provides different calendar implementations, and conversions to and from ISO for each.

**Comment by naftulikay** [comment]
Great, thanks!
